---
defaultGroups:
    - adm
    - cdrom
    - sudo
    - dip
    - plugdev
    - lpadmin

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword:  false
doReusePassword:  false

availableShells:  /bin/bash
userShell:        /bin/bash

passwordRequirements:
    minLength: 1
    maxLength: -1
